version: '3'
services:
  web:
    build:
      context: .
      dockerfile: .docker/web.dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html:cached
    environment:
      CGD_ENV: DOCKER
  db:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    restart: always
    command: mysqld --sql_mode=""
    environment:
      MYSQL_ROOT_PASSWORD: test123
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    links:
      - db:db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: test123
      MYSQL_ROOT_PASSWORD: test123
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 1024M
      MAX_EXECUTION_TIME: 30000